version: "2"
services:
  node-app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - type: bind
        source: ./data/db/mongo
        target: /data/db
    # image: "node:14"
    # user: "node"
    # working_dir: /home/node/app
    # volumes:
    #   - ./myapp:/home/node/app
    # command: "npm start"
    # network_mode: 'host'
  # mysqldb:
  #       image: mysql:${MYSQL_VERSION}
  #       container_name: ${MYSQL_HOST}
  #       restart: always
  #       env_file:
  #           - ".env"
  #       environment:
  #           - MYSQL_DATABASE=${MYSQL_DATABASE}
  #           - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #           - MYSQL_USER=${MYSQL_USER}
  #           - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #           - TZ=${MYSQL_TIMEZONE}
  #       ports:
  #           - "8989:3306"
  #       volumes:
  #           - "./etc/mysql/conf.d/my-local.cnf:/etc/mysql/conf.d/my-local.cnf"
  #           - "./data/db/mysql:/var/lib/mysql"
  #       networks:
  #           - default